### ISSUE TITLE
Using other localisable variables in the URL

### ISSUE THREAD

**Issue by floristenhove** [voorhoede/datocms-plugin-preview-links#2]
Hey guys,

First of all: great work on the plugin! We had something like this on our roadmap as well, but haven't gotten around to it yet so a big thank you is in order.

We have a use case which is currently not covered I think and I was wondering if you have considered it and if it's even possible: We use fully localised URLs and it looks like this is not supported by your plugin. E.g. we have a URL for an `Article` record in two languages: 
* nl: `https://www.website.com/nl/actueel/lokale-slug-van-artikel`
* en: `https://www.website.com/en/latest/local-article-slug`

Now the `locale` and `slug` in the URLs above can be configured using your plugin but the path of the parent page can not (`actueel` / `latest`). It is not part of the model unfortunately so we can not use a `fieldKey` value here. We would need a way to define custom variables per locale here as well. Have you thought about this use case and is there a way to support it? We're happy to create a PR but before doing so I would like to pick your brain about it.

A work-around could be to add fields to the model per locale that contain this value and hide those fields from editors but it feels a bit hacky. Hopefully there's a more elegant solution.

**Comment by Siilwyn** [comment]
:wave: hi @floristenhove! Curious, what solution did you go with?

I am looking into making this plugin (or a new one) with a more general approach of taking in template literals as input with JSON values on the model input too. So for example: the data `paths`: `{"en": "latest"}` can be used in the url field like so: `/${paths[locale]}/${slug}`.

Thoughts?

**Comment by floristenhove** [comment]
Hi @Siilwyn ! We’ve solved this creating our own version of the gatsby preview plugin. When it’s ready to be shared we will. Happy holidays!

**Comment by Siilwyn** [comment]
Alright thanks, happy holidays!
