### ISSUE TITLE
Links are not shown in the sidebar

### ISSUE THREAD

**Issue by PrimozRome** [voorhoede/datocms-plugin-preview-links#5]
Am I doing something wrong?

1. Plugin setup
<img width="2032" alt="Screenshot 2022-04-29 at 09 17 06" src="https://user-images.githubusercontent.com/1180467/165900487-95383c98-a211-4d4d-be1c-a36b396998ee.png">

2. JSON field setup
<img width="2032" alt="Screenshot 2022-04-29 at 09 15 41" src="https://user-images.githubusercontent.com/1180467/165900528-aa7a1196-aeee-4223-9668-f87b5077f103.png">

3. Link preview in the model
<img width="2032" alt="Screenshot 2022-04-29 at 09 15 31" src="https://user-images.githubusercontent.com/1180467/165900601-b35caeba-e179-427b-8cd9-715f30f0979e.png">

**Comment by velomovies** [comment]
Hi @PrimozRome, did you use the full-access api token? DatoCMS changed some security settings and getting the build triggers (where the url is based on) is only accessible via the full-access api token

**Comment by JeromeDevillers** [comment]
Hi @PrimozRome , 

Did you solve your issue ? I had same issue and notice that it was because I don't configured the depoyment build triggers.
I can see on your screenshot that you have the little arrow next to your logo ( top left ) missing so I think it's maybe your issue.
